package org.brylex.parser.processor;

import com.squareup.javapoet.ClassName;
import com.squareup.javapoet.CodeBlock;
import com.squareup.javapoet.JavaFile;
import com.squareup.javapoet.MethodSpec;
import com.squareup.javapoet.ParameterizedTypeName;
import com.squareup.javapoet.TypeSpec;
import com.squareup.javapoet.WildcardTypeName;

import javax.annotation.processing.ProcessingEnvironment;
import javax.lang.model.element.Modifier;
import javax.tools.StandardLocation;
import java.io.IOException;
import java.io.Writer;
import java.util.List;
import java.util.Map;

public final class RegistryCodeGenerator {

    private final ProcessingEnvironment env;

    public RegistryCodeGenerator(ProcessingEnvironment env) {
        this.env = env;
    }

    public void generate(String packageName, String simpleName, List<HandlerModel> models, String fingerprint)
            throws IOException {

        ClassName factory = ClassName.get("org.brylex.parser", "PathParserFactory");
        ParameterizedTypeName mapType = ParameterizedTypeName.get(
                ClassName.get(Map.class),
                ParameterizedTypeName.get(ClassName.get(Class.class), WildcardTypeName.subtypeOf(Object.class)),
                factory);

        ClassName hashMap = ClassName.get("java.util", "HashMap");

        MethodSpec.Builder factoriesMethod = MethodSpec.methodBuilder("factories")
                .addAnnotation(Override.class)
                .addModifiers(Modifier.PUBLIC)
                .returns(mapType);

        if (models.isEmpty()) {
            factoriesMethod.addStatement("return $T.of()", Map.class);
        } else {
            factoriesMethod.addStatement("$T<$T, $T> m = new $T<>()", Map.class,
                    ParameterizedTypeName.get(ClassName.get(Class.class), WildcardTypeName.subtypeOf(Object.class)),
                    factory, hashMap);
            for (HandlerModel m : models) {
                ClassName handler = ClassName.get(m.handlerType());
                ClassName generated = ClassName.get(m.packageName(), m.generatedClassName());
                factoriesMethod.addStatement("m.put($T.class, new $T())", handler, generated);
            }
            factoriesMethod.addStatement("return m");
        }

        MethodSpec fingerprintMethod = MethodSpec.methodBuilder("fingerprint")
                .addAnnotation(Override.class)
                .addModifiers(Modifier.PUBLIC)
                .returns(String.class)
                .addStatement("return $S", fingerprint)
                .build();

        TypeSpec spec = TypeSpec.classBuilder(simpleName)
                .addJavadoc("Generated by path-parser-processor — do not edit manually\n")
                .addModifiers(Modifier.PUBLIC, Modifier.FINAL)
                .addSuperinterface(ClassName.get("org.brylex.parser", "PathParserFactoryRegistry"))
                .addMethod(factoriesMethod.build())
                .addMethod(fingerprintMethod)
                .build();

        JavaFile.builder(packageName, spec).build().writeTo(env.getFiler());

        try (Writer w = env.getFiler()
                .createResource(StandardLocation.CLASS_OUTPUT, "",
                        "META-INF/services/org.brylex.parser.PathParserFactoryRegistry")
                .openWriter()) {
            w.write(packageName + "." + simpleName + "\n");
        }
    }
}
