package test;

import java.lang.Class;
import java.lang.Object;
import java.lang.Override;
import java.util.Map;
import java.util.function.Function;
import org.brylex.parser.InvokerSet;
import org.brylex.parser.ParseNode;
import org.brylex.parser.PathParserFactory;
import org.brylex.parser.TextInvoker;

/**
 * Generated by path-parser-processor — do not edit manually
 */
public final class SimpleHandler_PathParser implements PathParserFactory {
  private static final ParseNode TREE = buildTree();

  private static ParseNode buildTree() {
    ParseNode root = new ParseNode("/", null, null);
    ParseNode n_root = root.addChild("root", null, null);
    ParseNode n_root_child = n_root.addChild("child", null, null);
    n_root_child.needsText = true;
    return root;
  }

  @Override
  public Class<?> handlerType() {
    return SimpleHandler.class;
  }

  @Override
  public ParseNode tree() {
    return TREE;
  }

  @Override
  public InvokerSet bind(Object handler, Function<Class<?>, Object> subHandlerFactory,
      Function<Class<?>, PathParserFactory> subFactoryLookup) {
    SimpleHandler h = (SimpleHandler) handler;
    TREE.lookupChild("root", 0, null, null).lookupChild("child", 0, null, null).endInvokers.add(new TextInvoker(text -> h.child = text));
    return new InvokerSet(handler, Map.of());
  }

  @Override
  public ParseNode bindFresh(Object handler, Function<Class<?>, Object> subHandlerFactory,
      Function<Class<?>, PathParserFactory> subFactoryLookup) {
    ParseNode freshTree = buildTree();
    SimpleHandler h = (SimpleHandler) handler;
    freshTree.lookupChild("root", 0, null, null).lookupChild("child", 0, null, null).endInvokers.add(new TextInvoker(text -> h.child = text));
    return freshTree;
  }
}
